# Generated by Django 4.1.7 on 2023-04-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
