# Generated by Django 4.1.7 on 2023-04-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_question_answer_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
