# Generated by Django 4.2.1 on 2023-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
