# Generated by Django 4.2.1 on 2023-07-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
